apiVersion: batch/v1
kind: Job
metadata:
   name: chrombpnet.hepg2.128.4.1234.0.8.fold.1.dil.9.samepad
   labels:
     jobgroup: jobexample
spec:
   template:
     metadata:
       name: jobexample
       labels:
         jobgroup: jobexample
     spec:
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
               matchExpressions:
               - key: gpu-type
                 operator: In
                 values:
                 - "titan-xp"
                 - "K40"
                 - "TITANRTX"
                 - "K40"
                 - "V100"
                 - "A100"
                 - "A40"
                 - "A40"
                 - "RTX6000"
                 - "3090"
       containers:
       - name: jobexample
         image: kundajelab/chrombpnet:dev 
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 1
             memory: 32Gi
             nvidia.com/gpu: 1
           limits:
             cpu: 1
             memory: 64Gi
             nvidia.com/gpu: 1
         command:
         - /bin/bash
         - -c
         args:
         - nvidia-smi;
           mkdir /scratch/;
           cp -r /chrombpnet/chrombpnet/ /scratch/;
           cd /scratch/chrombpnet/;
           mkdir /scratch/chrombpnet/HEPG2/; 
           mkdir /scratch/chrombpnet/HEPG2/fold_1/; 
           cp -r /chrombpnet/ATAC_PE/HEPG2/data/ /scratch/chrombpnet/HEPG2/;
           cp  /chrombpnet/ATAC_PE/HEPG2/HEPG2_05.20.2022_bias_128_4_1234_0.8_fold_1/bias_model/bias.h5 /scratch/chrombpnet/HEPG2/fold_1/;
           cp -r /chrombpnet/reference/ /scratch/chrombpnet/;
           cp -r /chrombpnet/splits/ /scratch/chrombpnet/;
           bash atac_run_withbias_same_pad.sh 1234 HEPG2 1 9 fold_1/bias.h5;
           cp -r /scratch/chrombpnet/models/* /chrombpnet/ATAC_PE/HEPG2/; 
         volumeMounts:
         - mountPath: /chrombpnet
           name: chrombpnet
       restartPolicy: Never
       volumes:
         - name: chrombpnet
           persistentVolumeClaim:
             claimName: chrombpnet
       imagePullSecrets:
       - name: regcred
