apiVersion: batch/v1
kind: Job
metadata:
   name: dnase.k562.fold.4.dil.10.onlypos.samepad
   labels:
     jobgroup: jobexample
spec:
   template:
     metadata:
       name: jobexample
       labels:
         jobgroup: jobexample
     spec:
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 2
             preference:
               matchExpressions:
               - key: nvidia.com/gpu.product
                 operator: In
                 values:
                 - "titan-xp"
                 - "TITANRTX"
                 - "V100"
                 operator: NotIn
                 values:
                 - "NVIDIA-A100-PCIE-40GB-MIG-2g.10gb"
       containers:
       - name: jobexample
         image: kundajelab/chrombpnet:dev 
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 1
             memory: 32Gi
             nvidia.com/gpu: 1
           limits:
             cpu: 1
             memory: 128Gi
             nvidia.com/gpu: 1
         command:
         - /bin/bash
         - -c
         args:
         - nvidia-smi;
           mkdir /scratch/;
           cp -r /chrombpnet/chrombpnet/ /scratch/;
           cd /scratch/chrombpnet/;
           mkdir /scratch/chrombpnet/K562/; 
           mkdir /scratch/chrombpnet/K562/fold_4/; 
           cp -r /chrombpnet/DNASE_PE/K562/data/ /scratch/chrombpnet/K562/;
           cp  /chrombpnet/DNASE_PE/HEPG2/HEPG2_06.09.2022_bias_128_4_1234_0.8_fold_4/bias_model/bias.h5 /scratch/chrombpnet/K562/fold_4/;
           cp -r /chrombpnet/reference/ /scratch/chrombpnet/;
           cp -r /chrombpnet/splits/ /scratch/chrombpnet/;
           bash dnase_run_withbias_same_pad_only_pos.sh 1234 K562 4 10 fold_4/bias.h5 DNASE_PE;
           cp -r /scratch/chrombpnet/models/* /chrombpnet/DNASE_PE/K562/; 
         volumeMounts:
         - mountPath: /chrombpnet
           name: chrombpnet
       restartPolicy: Never
       volumes:
         - name: chrombpnet
           persistentVolumeClaim:
             claimName: chrombpnet
       imagePullSecrets:
       - name: regcrew
