apiVersion: v1
kind: Pod
metadata:
  name: populate-chrombpnet-pod 
spec:
  containers:
  - name: populate-pod-container
    image: kundajelab/chrombpnet:latest
    resources:
      requests:
        cpu: 1
        memory: 20Gi
      limits:
        cpu: 1
        memory: 20Gi
    command:
    - /bin/bash
    - -c
    args:
    - sleep infinity;
    volumeMounts:
    - mountPath: /chrombpnet
      name: chrombpnet
  restartPolicy: Never
  volumes:
    - name: chrombpnet
      persistentVolumeClaim:
        claimName: chrombpnet
  imagePullSecrets:
  - name: regcrew
