apiVersion: batch/v1
kind: Job
metadata:
   name: dnase.$clsmall.hepg2.transfer.fold.$fold.dil.$dil
   labels:
     jobgroup: jobexample
spec:
   template:
     metadata:
       name: jobexample
       labels:
         jobgroup: jobexample
     spec:
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
               matchExpressions:
               - key: gpu-type
                 operator: In
                 values:
                 - "titan-xp"
                 - "K40"
                 - "TITANRTX"
                 - "K40"
                 - "V100"
                 - "A100"
                 - "A40"
                 - "A40"
                 - "RTX6000"
                 - "3090"
       containers:
       - name: jobexample
         image: kundajelab/chrombpnet:dev 
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 1
             memory: 64Gi
             nvidia.com/gpu: 1
           limits:
             cpu: 1
             memory: 128Gi
             nvidia.com/gpu: 1
         command:
         - /bin/bash
         - -c
         args:
         - nvidia-smi;
           mkdir /scratch/;
           cp -r /chrombpnet/chrombpnet/ /scratch/;
           cd /scratch/chrombpnet/;
           mkdir /scratch/chrombpnet/$cellline/; 
           mkdir /scratch/chrombpnet/$cellline/fold_0/; 
           cp -r /chrombpnet/$data_type/$cellline/data/ /scratch/chrombpnet/$cellline/;
           cp  /chrombpnet/DNASE_PE/HEPG2/HEPG2_06.08.2022_bias_128_4_1234_0.8_fold_0/bias_model/bias.h5 /scratch/chrombpnet/$cellline/fold_0/;
           cp -r /chrombpnet/reference/ /scratch/chrombpnet/;
           cp -r /chrombpnet/splits/ /scratch/chrombpnet/;
           bash dnase_run_withbias.sh 1234 $cellline 0 $dil 2114 fold_0/bias.h5 $data_type;
           cp -r /scratch/chrombpnet/models/* /chrombpnet/ATAC_PE/$cellline/; 
         volumeMounts:
         - mountPath: /chrombpnet
           name: chrombpnet
       restartPolicy: Never
       volumes:
         - name: chrombpnet
           persistentVolumeClaim:
             claimName: chrombpnet
       imagePullSecrets:
       - name: regcrew
