apiVersion: batch/v1
kind: Job
metadata:
   name: chrombpnet.$clsmall.fold.$fold.bias.transfer
   labels:
     jobgroup: jobexample
spec:
   template:
     metadata:
       name: jobexample
       labels:
         jobgroup: jobexample
     spec:
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
               matchExpressions:
               - key: gpu-type
                 operator: In
                 values:
                 - "titan-xp"
                 - "K40"
                 - "TITANRTX"
                 - "K40"
                 - "V100"
                 - "A100"
                 - "A40"
                 - "A40"
                 - "RTX6000"
                 - "3090"
       containers:
       - name: jobexample
         image: kundajelab/chrombpnet:latest 
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 1
             memory: 32Gi
             nvidia.com/gpu: 1
           limits:
             cpu: 1
             memory: 128Gi
             nvidia.com/gpu: 1
         command:
         - /bin/bash
         - -c
         args:
         - nvidia-smi;
           mkdir /scratch/;
           cp -r /chrombpnet/chrombpnet/ /scratch/;
           cd /scratch/chrombpnet/;
           mkdir /scratch/chrombpnet/$cellline_$datatype/; 
           mkdir /scratch/chrombpnet/$cellline_$datatype/fold_$fold/; 
           cp -r /chrombpnet/$datatype/$cellline/data/ /scratch/chrombpnet/$cellline_$datatype/;
           cp  /chrombpnet/$biasdatatype/$biascellline/$bias_setting/bias_model/$bias_name /scratch/chrombpnet/$cellline_$datatype/fold_$fold/;
           cp -r /chrombpnet/reference/ /scratch/chrombpnet/;
           cp -r /chrombpnet/splits/ /scratch/chrombpnet/;
           bash all_run_with_bias_gm12878_cellline.sh $cellline_$datatype/fold_$fold/$bias_name $seed $cellline $fold $datatype;
           cp -r /scratch/chrombpnet/models/* /chrombpnet/$datatype/$cellline/; 
         volumeMounts:
         - mountPath: /chrombpnet
           name: chrombpnet
       restartPolicy: Never
       volumes:
         - name: chrombpnet
           persistentVolumeClaim:
             claimName: chrombpnet
       imagePullSecrets:
       - name: regcrew
