apiVersion: batch/v1
kind: Job
metadata:
   name: chrombpnet.k562.1234.0.5.fold.4.dnase
   labels:
     jobgroup: jobexample
spec:
   template:
     metadata:
       name: jobexample
       labels:
         jobgroup: jobexample
     spec:
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
               matchExpressions:
               - key: gpu-type
                 operator: In
                 values:
                 - "titan-xp"
                 - "TITANRTX"
                 - "V100"
       containers:
       - name: jobexample
         image: kundajelab/chrombpnet:dev 
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 1
             memory: 32Gi
             nvidia.com/gpu: 1
           limits:
             cpu: 1
             memory: 128Gi
             nvidia.com/gpu: 1
         command:
         - /bin/bash
         - -c
         args:
         - nvidia-smi;
           mkdir /scratch/;
           cp -r /chrombpnet/chrombpnet/ /scratch/;
           cd /scratch/chrombpnet/;
           mkdir /scratch/chrombpnet/K562_DNASE_PE/; 
           cp -r /chrombpnet/DNASE_PE/K562/data/ /scratch/chrombpnet/K562_DNASE_PE/;
           cp -r /chrombpnet/reference/ /scratch/chrombpnet/;
           cp -r /chrombpnet/splits/ /scratch/chrombpnet/;
           bash all_run.sh 128 4 1234 0.5 K562 4 DNASE_PE;
           cp -r /scratch/chrombpnet/models/* /chrombpnet/DNASE_PE/K562/; 
         volumeMounts:
         - mountPath: /chrombpnet
           name: chrombpnet
       restartPolicy: Never
       volumes:
         - name: chrombpnet
           persistentVolumeClaim:
             claimName: chrombpnet
       imagePullSecrets:
       - name: regcrew

